-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "PurchaseRawFruit",
    [2] = "Bomb-Bomb"
}

game:GetService("ReplicatedStorage").Remotes.CommF_:InvokeServer(unpack(args))
